"$schema" = "./config-schema.json"

add_newline = false
scan_timeout = 100
format = """
(${custom.username}${custom.lsf}$git_branch$git_status$cmd_duration$python\n)$directory
$character"""

[custom.username]
when = 'for u in $LOADOUT_CFG_STARSHIP_USERIDS_TO_HIGHLIGHT; do [ "$(whoami)" = "$u" ] && exit 0; done; exit 1'
command = 'whoami'
format = "[$output]($style) "
style = "bold yellow"

[custom.lsf]
when = 'test -n "$LSB_JOBID"'
command = "hostname -s"
format = "[LSF:$output]($style) "
style = "bold red"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold cyan"
format = "[$path]($style) "

[git_branch]
style = "bold blue"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 2000
style = "bold violet"
format = "[took $duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[python]
symbol = "🐍"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))](bold yellow) '
pyenv_prefix = "venv "
