# Valid values for LOADOUT_CFG_PREFERRED_LS: eza, lsd, ls
export LOADOUT_CFG_PREFERRED_BASH="" # Full path to preferred bash binary; re-execs at startup if set
export LOADOUT_CFG_PREFERRED_LS="eza"
export LOADOUT_CFG_PREFERRED_VI="nvim"
export LOADOUT_CFG_PREFERRED_CAT="bat"
export LOADOUT_CFG_ATTACH_TO_TMUX="0"
export LOADOUT_CFG_ATTACH_TO_TMUX_WITH_DETACH_OTHERS="0"
export LOADOUT_CFG_ENABLE_TMUX_PATH_STORE="1"
export LOADOUT_CFG_PROMPT_INCLUDE_HOST="0"
export LOADOUT_CFG_PROMPT_COLOR_NORMAL="$PROMPT_YELLOW"
export LOADOUT_CFG_PROMPT_COLOR_FARM="$PROMPT_RED"
export LOADOUT_CFG_ENABLE_FASTNVIM="0"
export LOADOUT_CFG_ENABLE_FZF="0"
export LOADOUT_CFG_ENABLE_ZOXIDE="0"
export LOADOUT_CFG_ENABLE_GRC="1"
export LOADOUT_CFG_ENABLE_STARSHIP="1"
export LOADOUT_CFG_STARSHIP_USERIDS_TO_HIGHLIGHT=""
# LOADOUT_CFG_ENABLE_ONLINE_UPDATES -> auto | 1 | 0
export LOADOUT_CFG_ENABLE_ONLINE_UPDATES="auto"
# LOADOUT_CFG_ONLINE_DETECT_TIMEOUT -> seconds per host (GNU timeout; decimal ok)
export LOADOUT_CFG_ONLINE_DETECT_TIMEOUT="0.15"
# LOADOUT_CFG_ONLINE_DETECT_HOSTS -> space-separated host:port
export LOADOUT_CFG_ONLINE_DETECT_HOSTS="github.com:443 raw.githubusercontent.com:443 pypi.org:443"
# LOADOUT_CFG_USE_LOADOUT_MODULES -> 0 | 1  (source modules-init.bash; opt-in)
export LOADOUT_CFG_USE_LOADOUT_MODULES="0"
