# loadout(1) bash completion -- GENERATED by `loadout completion bash`.
# Static snapshot of subcommands, flags, and registry names. Do not hand-edit;
# regenerate with `loadout completion bash > loadout.bash` when the CLI verbs,
# flags, or the package registry change.

__loadout_filedir() {
    if declare -F _filedir >/dev/null 2>&1; then
        _filedir
    else
        mapfile -t COMPREPLY < <(compgen -f -- "$cur")
    fi
}

_loadout_complete() {
    local cur prev words cword i
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD

    local verbs="install reinstall upgrade update list search info describe resolve doctor snapshot clean completion"
    local pkgs="agent-deck amux bash bash-docs bat biome broot btm btop bzip2 choose cicwave clang cloc dasel delta duf dust env-autohotkey env-bash env-cargo env-editorconfig env-helix env-nvim env-pip env-powershell env-st env-starship env-tcsh env-tmux env-vim env-wezterm env-zsh espresso expect eza fd fio firefox fish flameshot font-cascadiacode font-dejavusansmono font-envycoder font-firacode font-hack font-inconsolata font-iosevkaterm font-jetbrainsmono font-meslolg font-robotomono font-sourcecodepro font-ubuntumono fresh fzf git-nvim glow gnu-coreutils gnuplot gobject-typelibs gocheat gopls gping gtkwave gui_libs gvim htop hx hyperfine ipython iverilog jq jupyterlab just keyb klayout lazygit lefdef-tools less liberty-filter liberty-tools llvm-bolt lua-language-server markdown-oxide mate-terminal meld mesa3d_libs micro miller models modules ncdu nedit-ng ngspice ninja nodejs numr nvim nvim-plugin-stash nvim-qt octave openroad openssh p7zip parity-plot patchelf pdftotext pigz portable-python procs pv pygwalker pyright restic rg rsync ruby ruff rust rust-analyzer rust-crate-store scc sd shellcheck shfmt spice-subckt-rc-reduce st starship stylua surfer taplo tcl text-serdes time-plot tk tkdiff tldr tldr-data tmux tmux-path-store tokei tree-sitter treesitter-parsers ty urxvt uv vcd-toggle-profiler verilator vim visidata wezterm xephyr xsel xterm yank yara yazi yosys yq zellij zoxide zsh"
    local groups="@all @all-environments @compression @core-cli @core-environments @data-bundles @dev-tools @eda @editor-cli @editor-gui @editor-suite @engineering-loadout @envs @envs-all @fonts-all @fonts-default @gui-suite @python-stack @python-tools-extra @rust @scientific @security @shared @shared-all @shells-optional @system-monitor all"
    local list_groups="@all @all-environments @compression @core-cli @core-environments @data-bundles @dev-tools @eda @editor-cli @editor-gui @editor-suite @engineering-loadout @envs @envs-all @fonts-all @fonts-default @gui-suite @python-stack @python-tools-extra @rust @scientific @security @shared @shared-all @shells-optional @system-monitor"
    local tags="agent automation backup benchmark browser build cache clipboard compat compiler compress core data dedup def desktop dev diff disk docs document eda editor elf env file font format gds git gobject gui hotkeys hpc javascript lang language layout lef liberty library lint llvm logic lsp lua markdown math minimizer monitor multiplexer nav net network notebook notes nvim oasis opengl optimizer pager parser pkg place-and-route plot profiler prompt python rc reduction reference repl rtl ruby runtime rust scientific screenshot scripting search security shell simulator spice ssh sync synthesis system terminal text timing tmux toml toolchain tui vcd verilog viewer visualization waveform x11"

    # Option that takes an argument -> complete the argument, not a new word.
    case "$prev" in
        --skip)
            mapfile -t COMPREPLY < <(compgen -W "$pkgs $groups" -- "$cur"); return ;;
        --tag)
            mapfile -t COMPREPLY < <(compgen -W "$tags" -- "$cur"); return ;;
        --dest-dir|--post-install-hook)
            __loadout_filedir; return ;;
        --install-follows-symlinks)
            mapfile -t COMPREPLY < <(compgen -W "yes no auto" -- "$cur"); return ;;
    esac

    # Locate the subcommand: first non-dash word after argv[0].
    local cmd=""
    for (( i=1; i < cword; i++ )); do
        case "${words[i]}" in
            -*) ;;
            *) cmd="${words[i]}"; break ;;
        esac
    done

    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            mapfile -t COMPREPLY < <(compgen -W "-h --help -V --version --verbose" -- "$cur")
        else
            mapfile -t COMPREPLY < <(compgen -W "$verbs" -- "$cur")
        fi
        return
    fi

    case "$cmd" in
        install|reinstall|upgrade|update)
            if [[ "$cur" == -* ]]; then
                mapfile -t COMPREPLY < <(compgen -W "--skip --no-deps --force --dry-run --no-backup --post-install-hook --install-follows-symlinks --dest-dir -h --help" -- "$cur")
            else
                mapfile -t COMPREPLY < <(compgen -W "$pkgs $groups" -- "$cur")
            fi
            ;;
        resolve)
            if [[ "$cur" == -* ]]; then
                mapfile -t COMPREPLY < <(compgen -W "--skip --no-deps --force -h --help" -- "$cur")
            else
                mapfile -t COMPREPLY < <(compgen -W "$pkgs $groups" -- "$cur")
            fi
            ;;
        info|describe)
            mapfile -t COMPREPLY < <(compgen -W "$pkgs $groups -h --help" -- "$cur")
            ;;
        list)
            if [[ "$cur" == -* ]]; then
                mapfile -t COMPREPLY < <(compgen -W "--groups --tag --installed -h --help" -- "$cur")
            elif [[ " ${words[*]} " == *" --groups "* ]]; then
                mapfile -t COMPREPLY < <(compgen -W "$list_groups" -- "$cur")
            else
                mapfile -t COMPREPLY < <(compgen -W "$pkgs" -- "$cur")
            fi
            ;;
        search)
            [[ "$cur" == -* ]] && mapfile -t COMPREPLY < <(compgen -W "--tag -h --help" -- "$cur")
            ;;
        doctor)
            mapfile -t COMPREPLY < <(compgen -W "-h --help" -- "$cur")
            ;;
        clean)
            mapfile -t COMPREPLY < <(compgen -W "--logs --pending --all -h --help" -- "$cur")
            ;;
        completion)
            mapfile -t COMPREPLY < <(compgen -W "bash -h --help" -- "$cur")
            ;;
        snapshot)
            local sub="" j
            for (( j=i+1; j < cword; j++ )); do
                case "${words[j]}" in
                    -*) ;;
                    *) sub="${words[j]}"; break ;;
                esac
            done
            if [[ -z "$sub" ]]; then
                if [[ "$cur" == -* ]]; then
                    mapfile -t COMPREPLY < <(compgen -W "-h --help" -- "$cur")
                else
                    mapfile -t COMPREPLY < <(compgen -W "create restore list" -- "$cur")
                fi
            elif [[ "$sub" == "restore" && "$cur" != -* ]]; then
                __loadout_filedir
            else
                mapfile -t COMPREPLY < <(compgen -W "--dest-dir -h --help" -- "$cur")
            fi
            ;;
    esac
}
complete -F _loadout_complete loadout
complete -F _loadout_complete ./loadout
